### ISSUE TITLE
Seeing battery indicator in Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by aivarannamaa** [pi-top/pi-topd#140]
Is it already possible to install pi-top support straight from Raspberry Pi OS Bullseye repos? Or should I follow https://knowledgebase.pi-top.com/knowledge/pi-top-and-raspberry-pi-os ?

**Comment by m-roberts** [comment]
Currently the packages are not available from Raspberry Pi's repositories. AFAIK, this is unlikely to change any time soon, although @angusjfw or @jcapona could correct me on that.

**Comment by jcapona** [comment]
hey @aivarannamaa - sorry for the late response. We don't have our core packages in the Raspberry Pi OS repositories; you can follow the instructions from this [Knowledge Base article](https://knowledgebase.pi-top.com/knowledge/pi-top-and-raspberry-pi-os) to learn how to install our packages if you want to use Raspberry Pi OS with your pi-top.

**Comment by aivarannamaa** [comment]
Thanks!

I had tried a Pi-top repository before, but back then it messed up my Python dependencies. This time it seems to be compatible with Bullseye.

`pt-device-support` was too heavy for me. `pi-topd` was just what I needed. Maybe you want to update your KB article to also mention the lightweight options?
