### ISSUE TITLE
"The 'pitop-common' distribution was not found" message.

### ISSUE THREAD

**Issue by Eirikur** [pi-top/pi-topd#177]
Hi guys, I'm simply trying to build and install on Pi OS Buster 64.
I'm using the 'setup.py build' then 'setup.py install' method after cloning the repository. 
It seems that the hangup is that pypi doesn't have a python3-pitop-common that is specified in your file py3dist-overrides.

Can you tell me how to get that package? The install requires it. I don't see it in your repos. 

Maybe the setup.py is obsolete? It could be broken and no one has tested on a clean machine without python3-pitop-common.

I'm pretty sure I can get this all running on 64-bit systems, but some help understanding this dependency would be great.

**Comment by jcapona** [comment]
Hey @Eirikur ; we've released 64-bit version of our packages so you can try to install them directly from our apt servers. We'll be posting about this in the pi-top forum in the next couple of days.

You can follow the instructions from this [Knowledge Base article](https://knowledgebase.pi-top.com/knowledge/pi-top-and-raspberry-pi-os) to install our apt repository in Raspberry Pi OS and what needs to be done to provide device support.

About the particular issue you found, I just created a PR that will fix it: https://github.com/pi-top/pi-topd/pull/178.  However, you might still find issues when building this particular package using the regular `setup.py` approach; you'll note that we version-lock some of the dependencies and they might not be available on pypi as we package them ourselves for Debian. Also, features of the package such as several system daemons and some dpkg-triggers are only included when installing the `deb` file.

**Comment by Eirikur** [comment]
Thanks, @jcapona! I should have done it that way. I have been expecting to do a bit of coding, so I started with the source repos. I'll do it the knowlegebase way so I can get it working. I'm sure that .debs can do a lot more sensible installation. I've been pretty unhappy with Python packages, lately, that can't be bothered to install their binary dependencies or put out sensible messages.

Can you provide the URL that I should use for your apt servers?

**Comment by Eirikur** [comment]
Ooops, of course it is there in the article, now that I am following it.
